SpletnaDrazba/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpletnaDrazba.Models;

namespace SpletnaDrazba.Controllers
{
    public class CategoryController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Category
        public ActionResult AllCategories()
        {
            return View();
        }

        public ActionResult SubCategories(int id)
        {
            List<String> listSubCategory = new List<string>();
            switch (id)
            {
                case 1:
                    
                    listSubCategory.Add("Tv Sprejemniki");
                    listSubCategory.Add("Akustika");
                    ViewData["Categories"] = listSubCategory;
                    break;
                case 2:
                    listSubCategory.Add("Prenosniki");
                    listSubCategory.Add("Tablični računalniki");
                    listSubCategory.Add("Komponente");
                    ViewData["Categories"] = listSubCategory;
                    break;
                case 3:
                    listSubCategory.Add("Stacionarna telefonija");
                    listSubCategory.Add("Mobilna telefonija");
                    ViewData["Categories"] = listSubCategory;
                    break;
            }
            return View();
        }

        public ActionResult CategoryItems(string category)
        {
            List<Drazba> drazbe = db.Drazbas.Where(d => d.Kategorija.Equals(category)).ToList();

            ViewData["Drazbe"] = drazbe;

            return View();
        }
    }
}

SpletnaDrazba/Controllers/DrazbaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SpletnaDrazba.Models;

namespace SpletnaDrazba.Controllers
{
    public class DrazbaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Drazba
        public ActionResult Index()
        {
            string userID = (string)Session["CurrentUserID"];
            List<Drazba> drazbe = db.Drazbas.Where(d => d.User.Id.Equals(userID)).ToList();
            return View(drazbe);
        }

        // GET: Drazba/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drazba drazba = db.Drazbas.Find(id);
            
            var ponudbe = db.Ponudba.Where(p => p.Drazba.Id == id);
            var zadnjaPonudba = ponudbe.OrderByDescending(p => p.Id).FirstOrDefault();
            
            if (drazba == null)
            {
                return HttpNotFound();
            }
            if (zadnjaPonudba == null)
            {
                ViewData["trenutnaPonudba"] = drazba.ZacetnaCena;
                double visanjePonudbe = drazba.ZacetnaCena / 10;

                ViewData["minPonudba"] = Math.Round(drazba.ZacetnaCena + visanjePonudbe);
            }
            else
            {
                ViewData["trenutnaPonudba"] = zadnjaPonudba.Znesek;
                decimal visanjePonudbe = zadnjaPonudba.Znesek / 10;
                ViewData["minPonudba"] = Math.Round(zadnjaPonudba.Znesek + visanjePonudbe);
            }
            return View(drazba);
        }

        // GET: Drazba/Create
        public ActionResult Create()
        {
            return View();
        }



        // POST: Drazba/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DatumOd,DatumDo,Ime,NazivPredmeta,Uporabnik,Opis,ZacetnaCena,Kategorija")] Drazba drazba, Picture picture)
        {
            string filePathList = "";
            int count = 0;
            int trenutniID = db.Drazbas.Max(item => item.Id)+1;
            foreach (var file in picture.Files)
            {
                if(file != null) { 
                    var filename = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), +trenutniID + filename);
                    string semicolumn = "";
                    if (count > 0)
                        semicolumn = ";";
                    filePathList = filePathList+semicolumn+"~/Content/images/"+ trenutniID + filename;
                    file.SaveAs(path);
                }
                count++;
            }
            if (ModelState.IsValid)
            {
                drazba.Slike = filePathList;
                var userId = Session["CurrentUserID"];
                var user = db.Users.Find(userId);
                drazba.User = user;
                db.Drazbas.Add(drazba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(drazba);
        }

        [HttpGet]
        public ActionResult OddajPonudbo(int id,decimal znesek)
        {
            Drazba drazba = db.Drazbas.Single(d => d.Id == id);
            Ponudba ponudba = new Ponudba();
            ponudba.Drazba = drazba;
            ponudba.Znesek = znesek;
            var userId = Session["CurrentUserID"];
            var user = db.Users.Find(userId);
            ponudba.User = user;
            ponudba.DatumOddaje = DateTime.Now;
            db.Ponudba.Add(ponudba);
            db.SaveChanges();
            return RedirectToAction("Details/"+id.ToString());
        }

        // GET: Drazba/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drazba drazba = db.Drazbas.Find(id);
            if (drazba == null)
            {
                return HttpNotFound();
            }
            return View(drazba);
        }

        // POST: Drazba/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DatumOd,DatumDo,Ime,NazivPredmeta,Uporabnik,Opis,ZacetnaCena,Kategorija")] Drazba drazba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(drazba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(drazba);
        }

        /*[HttpPost]
        public ActionResult Create(Picture picture)
        {
            foreach (var file in picture.Files)
            {
                var filename = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/images"),filename);
                file.SaveAs(path);
            }
            return RedirectToAction("Create");
        }*/

        // GET: Drazba/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drazba drazba = db.Drazbas.Find(id);
            if (drazba == null)
            {
                return HttpNotFound();
            }
            return View(drazba);
        }

        // POST: Drazba/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Drazba drazba = db.Drazbas.Find(id);
            db.Drazbas.Remove(drazba);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SpletnaDrazba/Views/Category/AllCategories.cshtml
@using Microsoft.Owin.Security.OAuth

@{
    ViewBag.Title = "AllCategories";
}

<h2>Kategorije</h2>
<div class="jumbotron" style="padding-top: 0%">
    <a href="@Url.Action("SubCategories", "Category",new { id = 1})">
        <h2>Avdio-video</h2>
        <img src="~/Content/images/audio-video-rentals.png" height="250px" width="80%"/>
    </a>
</div>
<div class="jumbotron" style="padding-top: 0%">
    <a href="@Url.Action("CategoryItems", "Category",new { category = "Auto-moto"})">
        <h2>Avto-moto</h2>
        <img src="~/Content/images/CLASS_SPORTS-CARS_PNG.png" height="250px" width="50%"/>
    </a>
</div>
<div class="jumbotron" style="padding-top: 0%">
    <a href="@Url.Action("SubCategories", "Category",new { id = 2})">
        <h2>Računalništvo</h2>
        <img src="~/Content/images/technologyobjects.png" height="250px" width="80%"/>
    </a>
</div>
<div class="jumbotron" style="padding-top: 0%">
    <a href="@Url.Action("CategoryItems", "Category",new { category = "Oblačila"})">
        <h2>Oblačila</h2>
        <img src="~/Content/images/clothesline-silhouette.png" height="250px" width="80%" />
    </a>
</div>
<div class="jumbotron" style="padding-top: 0%">
    <a href="@Url.Action("CategoryItems", "Category",new { category = "Dom"})">
        <h2>Dom</h2>
        <img src="~/Content/images/Home.png" height="250px" width="40%"/>
    </a>
</div>
<div class="jumbotron" style="padding-top: 0%">
    <a href="@Url.Action("CategoryItems", "Category",new { category = "Šport"})">
        <h2>Šport</h2>
        <img src="~/Content/images/sport.png" height="250px" width="60%"/>
    </a>
</div>
<div class="jumbotron" style="padding-top: 0%">
    <a href="@Url.Action("SubCategories", "Category",new { id = 3})">
        <h2>Telefonija</h2>
        <img src="~/Content/images/smartphones-png.png" height="250px" width="55%"/>
    </a>
</div>

SpletnaDrazba/Views/Category/CategoryItems.cshtml
@using SpletnaDrazba.Models

@{
    ViewBag.Title = "CategoryItems";
}

<h2>Predmeti kategorije</h2>

@{ List<Drazba> drazbe = (List<Drazba>)ViewData["Drazbe"];}

<table class="table">
    <tr>
        <th>
            Datum in ura začetka
        </th>
        <th>
            Datum in ura konca
        </th>
        <th>
            Ime Dražbe
        </th>
        <th>
            Naziv Predmeta
        </th>
        
        <th>
            Opis
        </th>
        <th>
            Začetna cena
        </th>
        <th>
           Kategorija
        </th>
        <th></th>
    </tr>

    @foreach (var item in drazbe)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DatumOd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumDo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NazivPredmeta)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZacetnaCena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kategorija)
            </td>
            <td>
                
                @Html.ActionLink("Details", "Details","Drazba", new { id = item.Id },null)  
            </td>
        </tr>
    }

</table>

SpletnaDrazba/Views/Category/SubCategories.cshtml
@{
    ViewBag.Title = "SubCategories";
}

<h2>SubCategories</h2>
@{ List<String> list = (List<String>) @ViewData["Categories"];}
@foreach (var category in list)
{
    <div class="jumbotron" style="padding-top: 0%">
        <a href="@Url.Action("CategoryItems", "Category",new { category = @category})">
            <h2>@category</h2>
            <img src="~/Content/images/@(category).png" height="250px" width="30%" />
        </a>
    </div>
}